import Color
class TetrisConstants:
	TEMPLATEWIDTH = 5
	TEMPLATEHEIGHT = 5

	Piece = namedtuple('Piece', ['template', 'color'])

	PIECES = {'S': (S_SHAPE_TEMPLATE, Color.YELLOW),
		  'Z': (Z_SHAPE_TEMPLATE, Color.WHITE),
		  'J': (J_SHAPE_TEMPLATE, Color.GREEN),
		  'L': (L_SHAPE_TEMPLATE, Color.RED),
		  'I': (I_SHAPE_TEMPLATE, Color.PURPLE),
		  'O': (O_SHAPE_TEMPLATE, Color.ORANGE),
		  'T': (T_SHAPE_TEMPLATE, Color.BLUE)}

	S_SHAPE_TEMPLATE = [['.....',
		             '.....',
		             '..OO.',
		             '.OO..',
		             '.....'],
		            ['.....',
		             '..O..',
		             '..OO.',
		             '...O.',
		             '.....']]

	Z_SHAPE_TEMPLATE = [['.....',
		             '.....',
		             '.OO..',
		             '..OO.',
		             '.....'],
		            ['.....',
		             '..O..',
		             '.OO..',
		             '.O...',
		             '.....']]

	I_SHAPE_TEMPLATE = [['..O..',
		             '..O..',
		             '..O..',
		             '..O..',
		             '.....'],
		            ['.....',
		             '.....',
		             'OOOO.',
		             '.....',
		             '.....']]

	O_SHAPE_TEMPLATE = [['.....',
		             '.....',
		             '.OO..',
		             '.OO..',
		             '.....']]

	J_SHAPE_TEMPLATE = [['.....',
		             '.O...',
		             '.OOO.',
		             '.....',
		             '.....'],
		            ['.....',
		             '..OO.',
		             '..O..',
		             '..O..',
		             '.....'],
		            ['.....',
		             '.....',
		             '.OOO.',
		             '...O.',
		             '.....'],
		            ['.....',
		             '..O..',
		             '..O..',
		             '.OO..',
		             '.....']]

	L_SHAPE_TEMPLATE = [['.....',
		             '...O.',
		             '.OOO.',
		             '.....',
		             '.....'],
		            ['.....',
		             '..O..',
		             '..O..',
		             '..OO.',
		             '.....'],
		            ['.....',
		             '.....',
		             '.OOO.',
		             '.O...',
		             '.....'],
		            ['.....',
		             '.OO..',
		             '..O..',
		             '..O..',
		             '.....']]

	T_SHAPE_TEMPLATE = [['.....',
		             '..O..',
		             '.OOO.',
		             '.....',
		             '.....'],
		            ['.....',
		             '..O..',
		             '..OO.',
		             '..O..',
		             '.....'],
		            ['.....',
		             '.....',
		             '.OOO.',
		             '..O..',
		             '.....'],
		            ['.....',
		             '..O..',
		             '.OO..',
		             '..O..',
		             '.....']]
